# Uncomment the next line to define a global platform for your project
platform :macos, '14.5'

target 'SecureMotion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SecureMotion
  pod 'CocoaMQTT'
  target 'SecureMotionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SecureMotionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
